stats = [
    'Action Speed',
    'Agility',
    'All Attributes',
    'Armor Penetration',
    'Armor Rating',
    'Buff Duration Bonus',
    'Debuff Duration Bonus',
    'Dexterity',
    'Knowledge',
    'Magic Penetration',
    'Magic Resistance',
    'Additional Magical Damage',
    'Magical Damage',
    'Magical Damage Bonus',
    'Magical Damage Reduction',
    'True Magical Damage',
    'Magical Healing',
    'Magical Interaction Speed',
    'Magical Power',
    'Max Health',
    'Max Health Bonus',
    'Additional Memory Capacity',
    'Memory Capacity Bonus',
    'Additional Move Speed',
    'Move Speed Bonus',
    'Additional Physical Damage',
    'Physical Damage Bonus',
    'Physical Damage Reduction',
    'True Physical Damage',
    'Physical Healing',
    'Physical Power',
    'Weapon Damage',
    'Projectile Damage Reduction',
    'Regular Interaction Speed',
    'Resourcefulness',
    'Spell Casting Speed',
    'Strength',
    'Vigor',
    'Will',
    'Move Speed',
    'Luck',
]